ALTER TABLE document_copies ADD COLUMN IF NOT EXISTS received_confirmed TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE document_copies ADD COLUMN IF NOT EXISTS received_on DATE NULL DEFAULT NULL;
ALTER TABLE document_copies ADD COLUMN IF NOT EXISTS signed_by VARCHAR(180) NULL DEFAULT NULL;